# Generated by Django 3.2.10 on 2022-02-10 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoreBoard',
            new_name='ScoreBoard_2',
        ),
    ]
