# Generated by Django 3.2.8 on 2022-07-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220210_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='Dark_Theam',
            field=models.BooleanField(default=False),
        ),
    ]
